---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/aywsolution/public_html/appemergencias.aywsolution.com/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/aywsolution/web_appemergencias/
      - /bin/rsync -av ./ $DEPLOYPATH