# ---
#   deployment:
#     tasks:
#       - export DEPLOYPATH=/home/gorel/public_html/appemergencias.regionloreto.gob.pe/
#       - /bin/rsync -av public/ $DEPLOYPATH
#       - export DEPLOYPATH=/home/gorel/web_appemergencias/
#       - /bin/rsync -av ./ $DEPLOYPATH

---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/aywsolution/public_html/appemergencias.aywsolution.com/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/aywsolution/web_appemergencias/
      - /bin/rsync -av ./ $DEPLOYPATH